In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.

print(np.__version__)
print(np.show_config())

1.17.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fran/miniconda3/envs/data_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fran/miniconda3/envs/data_env/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fran/miniconda3/envs/data_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fran/miniconda3/envs/data_env/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fran/miniconda3/envs/data_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fran/miniconda3/envs/data_env/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fran/miniconda3/envs/data_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fran/miniconda3/envs/data_env/inc

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))
b = np.empty((2,3,5))
#c = np.full((2,3,5), rand())

print(b)

[[[5.28556325e+180 1.57762309e+214 1.27827553e-152 1.13290758e-153
   1.57762309e+214]
  [2.02574529e-153 3.86598877e+233 2.45532631e+198 7.13146612e+252
   5.02620935e+180]
  [9.15000112e+199 6.05979497e+233 1.97947460e-258 2.44141101e-152
   6.79615843e+199]]

 [[2.06862031e+161 6.00002718e-310 0.00000000e+000 0.00000000e+000
   0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
   0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
   0.00000000e+000]]]


In [4]:
#4. Print a.
print(a)

[[[0.54743138 0.07403613 0.46332772 0.38189485 0.63634029]
  [0.57971686 0.15915918 0.79703004 0.40059876 0.22726735]
  [0.27493613 0.25220205 0.14090691 0.87696044 0.62437852]]

 [[0.09359747 0.28817447 0.42402703 0.34469672 0.83915845]
  [0.15546126 0.32357577 0.65890061 0.14574606 0.96856766]
  [0.33621304 0.64655076 0.76567727 0.38684403 0.81518399]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3))

In [6]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [7]:
#7. Do a and b have the same size? How do you prove that in Python code?
if a.size == b.size:
    print('Yes, they have the same size.')
else:
    print("No, they don't.")

Yes, they have the same size.


In [8]:
#8. Are you able to add a and b? Why or why not?
try:
    np.add(a,b)
except ValueError:
    print('Whatch out! You can not add them due to having different shapes')

Whatch out! You can not add them due to having different shapes


In [9]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.transpose(1,2,0)


In [10]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
try:
    d = np.add(a,c)
except ValueError:
    print('Whatch out! You can not add them to having different shapes')
else:
    print('It works because they have the same shape')

It works because they have the same shape


In [12]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print(d)

#D is the addition of a and c, thus, d is the same as a summing up 1.

[[[0.77396538 0.16867748 0.22405802 0.15528605 0.48296055]
  [0.26644222 0.79697371 0.63094071 0.66837926 0.88167553]
  [0.94491118 0.88177187 0.54908678 0.11355721 0.86979832]]

 [[0.52762864 0.93226806 0.99713155 0.33909117 0.4998042 ]
  [0.67912261 0.86209019 0.58784905 0.84332168 0.15476335]
  [0.61191296 0.67569358 0.42319846 0.94116431 0.07205386]]]
[[[1.77396538 1.16867748 1.22405802 1.15528605 1.48296055]
  [1.26644222 1.79697371 1.63094071 1.66837926 1.88167553]
  [1.94491118 1.88177187 1.54908678 1.11355721 1.86979832]]

 [[1.52762864 1.93226806 1.99713155 1.33909117 1.4998042 ]
  [1.67912261 1.86209019 1.58784905 1.84332168 1.15476335]
  [1.61191296 1.67569358 1.42319846 1.94116431 1.07205386]]]


In [11]:
#12. Multiply a and c. Assign the result to e.

e = np.multiply(a,c)

In [12]:
#13. Does e equal to a? Why or why not?
if e.all() == a.all():
    print('Yes, they are equal.')
else:
    print("No, they don't.")

Yes, they are equal.


In [20]:
##14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = d.max()
d_mean = d.mean()
d_min = d.min()

In [14]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))
print(f)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [15]:
print(d)

[[[1.54743138 1.07403613 1.46332772 1.38189485 1.63634029]
  [1.57971686 1.15915918 1.79703004 1.40059876 1.22726735]
  [1.27493613 1.25220205 1.14090691 1.87696044 1.62437852]]

 [[1.09359747 1.28817447 1.42402703 1.34469672 1.83915845]
  [1.15546126 1.32357577 1.65890061 1.14574606 1.96856766]
  [1.33621304 1.64655076 1.76567727 1.38684403 1.81518399]]]


In [46]:
[25 if n < 3 else 75 if n > 3 else 999 for n in [1, 2, 3, 4, 5]]

[25, 25, 999, 75, 75]

In [42]:
#16
list_f = [25 if y < d_mean and y > d_min else 75 if y > d_mean and y < d_max else 0 if y == d_min else 100 for i in d for x in i for y in x]


f = np.reshape(list_f,(2,3,5))

In [48]:
#17
print(d)
print(f)

[[[1.54743138 1.07403613 1.46332772 1.38189485 1.63634029]
  [1.57971686 1.15915918 1.79703004 1.40059876 1.22726735]
  [1.27493613 1.25220205 1.14090691 1.87696044 1.62437852]]

 [[1.09359747 1.28817447 1.42402703 1.34469672 1.83915845]
  [1.15546126 1.32357577 1.65890061 1.14574606 1.96856766]
  [1.33621304 1.64655076 1.76567727 1.38684403 1.81518399]]]
[[[ 75   0  75  25  75]
  [ 75  25  75  25  25]
  [ 25  25  25  75  75]]

 [[ 25  25  25  25  75]
  [ 25  25  75  25 100]
  [ 25  75  75  25  75]]]


In [45]:
#18
list_j = ['B' if y < d_mean and y > d_min else 'D' if y > d_mean and y < d_max else 'A' if y == d_min else 'E' for i in d for x in i for y in x]


j = np.reshape(list_j,(2,3,5))
print(j)

[[['D' 'A' 'D' 'B' 'D']
  ['D' 'B' 'D' 'B' 'B']
  ['B' 'B' 'B' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'D']
  ['B' 'B' 'D' 'B' 'E']
  ['B' 'D' 'D' 'B' 'D']]]



"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""




"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""